### PR TITLE
fix postupdate / preupdate hooks

### PR DESCRIPTION
**Pull request by Ivshti**
Will solve issue https://github.com/mafintosh/multi-master-merge/issues/9

### CODE REVIEW

**Comment by mafintosh** [comment]
The bug is actually that the `enc` from `(data, enc, cb)` is shadowing the `enc` var above. To fix the we should just rename the `enc` from `(data, enc, cb)` to `e` or `_`. You wanna update the PR?

**Comment by Ivshti** [comment]
Done.

**Comment by Ivshti** [comment]
Now this is intresting
```
SyntaxError: Unexpected token o
    at Object.parse (native)
    at Object.json.decode (/Users/ivogeorgiev/multipass-torrent/node_modules/multi-master-merge/encoders.js:6:17)
```

Meanwhile the previous encoding passed was utf8, and it initialized an encoder with utf8, while I'm using a JSON global encoder.
So this means we have to initialize new encoder within the callback with "enc".

The original solution was the correct one after all, too bad I force pushed it :D 

Will update PR again

**Comment by mafintosh** [comment]
I think this is related to another error. Could you post a full example?

**Comment by Ivshti** [comment]
No, it is not. enc inside the callback is "utf8", not "json". enc outside the callback is an encoder initialized with json, so we obviously can't use outside enc for something that's in utf8.

The full example is https://github.com/Ivshti/multipass-torrent, ran with 
```
node cli/multipass.js --source=https://torrentz.eu/feed_verified?q=
```
But I doubt such an example is needed. 

If you think that it's irregular that inside enc is "utf8" while I'm using json, then maybe we're talking about another issue.

**Comment by mafintosh** [comment]
The inner enc is coming from through2. It's not related to mmm at all - just a coincidence that it works :) I'll look into fixing this tomorrow morning

**Comment by Ivshti** [comment]
@mafintosh this is fixed, we both didn't notice that we had to decode entry.value instead of entry. 

Silly thing to have such a large discussion on :)

**Comment by mafintosh** [comment]
Fixed in 2.2.1 by https://github.com/mafintosh/multi-master-merge/commit/60d06e351fd84f4fb1e1afc554c2dff9bae9261b

**Comment by Ivshti** [comment]
@mafintosh closing this then

**Pull request closed without merging**
